# Use a multi-stage build
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy the source code
COPY . .
RUN npm run build
RUN npm install -g serve



# # Use an Nginx server to serve the static files
# FROM nginx:alpine
# COPY nginx.conf /etc/nginx/nginx.conf
# # Copy the build output to Nginx's HTML folder
# COPY --from=build /app/build /usr/share/nginx/html

# Copy the entrypoint script
COPY entrypoint.sh /app/entrypoint.sh

# Convert from CRLF to LF
RUN sed -i 's/\r$//g' /app/entrypoint.sh

# Make the script executable
RUN chmod +x /app/entrypoint.sh

# Expose port 8080
EXPOSE 8080

# Set the custom entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]
