# Generated by Django 5.1.6 on 2025-03-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployments',
            name='google_cli_key',
            field=models.TextField(blank=True),
        ),
    ]
