# Generated by Django 5.1.6 on 2025-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deployments_google_cli_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableStacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('variant', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
