# Generated by Django 5.1.6 on 2025-03-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_availablestacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacks',
            name='type',
        ),
        migrations.RemoveField(
            model_name='stacks',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='stacks',
            name='version',
        ),
        migrations.AddField(
            model_name='stacks',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.availablestacks'),
            preserve_default=False,
        ),
    ]
