# Generated by Django 5.1.6 on 2025-03-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_stack_stacks_purchased_stack_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacks',
            name='google_cli_key',
            field=models.TextField(null=True),
        ),
    ]
