# Generated by Django 5.1.6 on 2025-03-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stacks_google_cli_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeploymentFrontend',
            new_name='StackBackends',
        ),
        migrations.RenameModel(
            old_name='DeploymentDatabase',
            new_name='StackDatabases',
        ),
        migrations.RenameModel(
            old_name='DeploymentBackend',
            new_name='StackFrontends',
        ),
    ]
