# Generated by Django 5.1.6 on 2025-03-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_deploymentfrontend_stackbackends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stacks',
            old_name='purchased_stack_id',
            new_name='purchased_stack',
        ),
    ]
