# Generated by Django 5.1.6 on 2025-03-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_purchased_stack_id_stacks_purchased_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='stacks',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
