# Generated by Django 5.1.6 on 2025-03-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stacks_google_cli_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackbackends',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='stackdatabases',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='stackfrontends',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='stacks',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='stacks',
            name='google_cli_key',
        ),
        migrations.AddField(
            model_name='stackbackends',
            name='stack',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.stacks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stackdatabases',
            name='stack',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.stacks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stackfrontends',
            name='stack',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.stacks'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Deployments',
        ),
    ]
