# Generated by Django 5.1.6 on 2025-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_stackbackends_deployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablestacks',
            name='price_id',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
