# Generated by Django 5.1.6 on 2025-03-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_cli_key',
            field=models.TextField(blank=True),
        ),
    ]
