# Generated by Django 5.1.6 on 2025-03-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_google_cli_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_cli_key',
        ),
    ]
