# Generated by Django 5.1.6 on 2025-03-17 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stacks_google_cli_key'),
        ('github', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GitHubToken',
            new_name='Tokens',
        ),
        migrations.RenameModel(
            old_name='GitHubWebhookEvent',
            new_name='WebhookEvents',
        ),
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=255)),
                ('webhook_id', models.IntegerField(unique=True)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stacks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GitHubWebhook',
        ),
    ]
