# Generated by Django 5.1.6 on 2025-03-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stacks_google_cli_key'),
        ('github', '0002_rename_githubtoken_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevents',
            name='repository',
        ),
        migrations.AddField(
            model_name='webhookevents',
            name='stack',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.stacks'),
            preserve_default=False,
        ),
    ]
