# Generated by Django 5.1.6 on 2025-03-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_mern',
            field=models.BooleanField(default=False),
        ),
    ]
