# Generated by Django 5.1.6 on 2025-03-06 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_deployments_delete_deployedstacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployments',
            name='stack_type',
        ),
        migrations.AddField(
            model_name='deployments',
            name='stack',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.stacks'),
            preserve_default=False,
        ),
    ]
