# Generated by Django 5.1.6 on 2025-03-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_remove_deployments_backend_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentbackend',
            name='image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploymentdatabase',
            name='project_id',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploymentfrontend',
            name='image_url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
