# Generated by Django 5.1.6 on 2025-03-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_deploymentbackend_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentdatabase',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='deploymentfrontend',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='deployments',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='deployments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stacks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeploymentBackend',
        ),
        migrations.DeleteModel(
            name='DeploymentDatabase',
        ),
        migrations.DeleteModel(
            name='DeploymentFrontend',
        ),
        migrations.DeleteModel(
            name='Deployments',
        ),
        migrations.DeleteModel(
            name='Stacks',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
